-- SQL dataset with 50 recipes

-- Assuming tables already exist

INSERT INTO recipes (author, title, banner_image_url, servings, prep_time, cook_time, rest_time, difficulty) VALUES
('alice', 'Ricetta Placeholder 01', 'https://example.com/recipe01.jpg', 2, 6, 11, NULL, 'medium'),
('carol', 'Ricetta Placeholder 02', 'https://example.com/recipe02.jpg', 3, 7, 12, NULL, 'hard'),
('alice', 'Ricetta Placeholder 03', 'https://example.com/recipe03.jpg', 4, 8, 13, NULL, 'easy'),
('carol', 'Ricetta Placeholder 04', 'https://example.com/recipe04.jpg', 5, 9, 14, NULL, 'medium'),
('alice', 'Ricetta Placeholder 05', 'https://example.com/recipe05.jpg', 1, 10, 15, NULL, 'hard'),
('carol', 'Ricetta Placeholder 06', 'https://example.com/recipe06.jpg', 2, 11, 16, NULL, 'easy'),
('alice', 'Ricetta Placeholder 07', 'https://example.com/recipe07.jpg', 3, 12, 17, NULL, 'medium'),
('carol', 'Ricetta Placeholder 08', 'https://example.com/recipe08.jpg', 4, 13, 18, NULL, 'hard'),
('alice', 'Ricetta Placeholder 09', 'https://example.com/recipe09.jpg', 5, 14, 19, NULL, 'easy'),
('carol', 'Ricetta Placeholder 10', 'https://example.com/recipe10.jpg', 1, 15, 20, NULL, 'medium'),
('alice', 'Ricetta Placeholder 11', 'https://example.com/recipe11.jpg', 2, 16, 21, NULL, 'hard'),
('carol', 'Ricetta Placeholder 12', 'https://example.com/recipe12.jpg', 3, 17, 22, NULL, 'easy'),
('alice', 'Ricetta Placeholder 13', 'https://example.com/recipe13.jpg', 4, 18, 23, NULL, 'medium'),
('carol', 'Ricetta Placeholder 14', 'https://example.com/recipe14.jpg', 5, 19, 24, NULL, 'hard'),
('alice', 'Ricetta Placeholder 15', 'https://example.com/recipe15.jpg', 1, 20, 25, NULL, 'easy'),
('carol', 'Ricetta Placeholder 16', 'https://example.com/recipe16.jpg', 2, 21, 26, NULL, 'medium'),
('alice', 'Ricetta Placeholder 17', 'https://example.com/recipe17.jpg', 3, 22, 27, NULL, 'hard'),
('carol', 'Ricetta Placeholder 18', 'https://example.com/recipe18.jpg', 4, 23, 28, NULL, 'easy'),
('alice', 'Ricetta Placeholder 19', 'https://example.com/recipe19.jpg', 5, 24, 29, NULL, 'medium'),
('carol', 'Ricetta Placeholder 20', 'https://example.com/recipe20.jpg', 1, 5, 30, NULL, 'hard'),
('alice', 'Ricetta Placeholder 21', 'https://example.com/recipe21.jpg', 2, 6, 31, NULL, 'easy'),
('carol', 'Ricetta Placeholder 22', 'https://example.com/recipe22.jpg', 3, 7, 32, NULL, 'medium'),
('alice', 'Ricetta Placeholder 23', 'https://example.com/recipe23.jpg', 4, 8, 33, NULL, 'hard'),
('carol', 'Ricetta Placeholder 24', 'https://example.com/recipe24.jpg', 5, 9, 34, NULL, 'easy'),
('alice', 'Ricetta Placeholder 25', 'https://example.com/recipe25.jpg', 1, 10, 35, NULL, 'medium'),
('carol', 'Ricetta Placeholder 26', 'https://example.com/recipe26.jpg', 2, 11, 36, NULL, 'hard'),
('alice', 'Ricetta Placeholder 27', 'https://example.com/recipe27.jpg', 3, 12, 37, NULL, 'easy'),
('carol', 'Ricetta Placeholder 28', 'https://example.com/recipe28.jpg', 4, 13, 38, NULL, 'medium'),
('alice', 'Ricetta Placeholder 29', 'https://example.com/recipe29.jpg', 5, 14, 39, NULL, 'hard'),
('carol', 'Ricetta Placeholder 30', 'https://example.com/recipe30.jpg', 1, 15, 10, NULL, 'easy'),
('alice', 'Ricetta Placeholder 31', 'https://example.com/recipe31.jpg', 2, 16, 11, NULL, 'medium'),
('carol', 'Ricetta Placeholder 32', 'https://example.com/recipe32.jpg', 3, 17, 12, NULL, 'hard'),
('alice', 'Ricetta Placeholder 33', 'https://example.com/recipe33.jpg', 4, 18, 13, NULL, 'easy'),
('carol', 'Ricetta Placeholder 34', 'https://example.com/recipe34.jpg', 5, 19, 14, NULL, 'medium'),
('alice', 'Ricetta Placeholder 35', 'https://example.com/recipe35.jpg', 1, 20, 15, NULL, 'hard'),
('carol', 'Ricetta Placeholder 36', 'https://example.com/recipe36.jpg', 2, 21, 16, NULL, 'easy'),
('alice', 'Ricetta Placeholder 37', 'https://example.com/recipe37.jpg', 3, 22, 17, NULL, 'medium'),
('carol', 'Ricetta Placeholder 38', 'https://example.com/recipe38.jpg', 4, 23, 18, NULL, 'hard'),
('alice', 'Ricetta Placeholder 39', 'https://example.com/recipe39.jpg', 5, 24, 19, NULL, 'easy'),
('carol', 'Ricetta Placeholder 40', 'https://example.com/recipe40.jpg', 1, 5, 20, NULL, 'medium'),
('alice', 'Ricetta Placeholder 41', 'https://example.com/recipe41.jpg', 2, 6, 21, NULL, 'hard'),
('carol', 'Ricetta Placeholder 42', 'https://example.com/recipe42.jpg', 3, 7, 22, NULL, 'easy'),
('alice', 'Ricetta Placeholder 43', 'https://example.com/recipe43.jpg', 4, 8, 23, NULL, 'medium'),
('carol', 'Ricetta Placeholder 44', 'https://example.com/recipe44.jpg', 5, 9, 24, NULL, 'hard'),
('alice', 'Ricetta Placeholder 45', 'https://example.com/recipe45.jpg', 1, 10, 25, NULL, 'easy'),
('carol', 'Ricetta Placeholder 46', 'https://example.com/recipe46.jpg', 2, 11, 26, NULL, 'medium'),
('alice', 'Ricetta Placeholder 47', 'https://example.com/recipe47.jpg', 3, 12, 27, NULL, 'hard'),
('carol', 'Ricetta Placeholder 48', 'https://example.com/recipe48.jpg', 4, 13, 28, NULL, 'easy'),
('alice', 'Ricetta Placeholder 49', 'https://example.com/recipe49.jpg', 5, 14, 29, NULL, 'medium'),
('carol', 'Ricetta Placeholder 50', 'https://example.com/recipe50.jpg', 1, 15, 30, NULL, 'hard');
